version: '2.4'
services:
  pokedex:
    build: ./
    container_name: graphql-pokemon
    image: 'favware/graphql-pokemon:latest'
    networks:
      - pokedex
    ports:
      - '8080:4000'
    restart: 'no'

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London
    ports:
      - '8191:8191'
    restart: no

networks:
  pokedex:
